name: "Test local with conditionals"
on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  local_test_options:
    strategy:
      fail-fast: false
      matrix:
        version: ["1.7.0", "1.8.2", "1.9.0", "1.10.0", "1.11.0", "latest"]
    runs-on: ubuntu-latest
    env:
      BATS_LIB_PATH: "/usr/lib"
      TERM: xterm
    name: local with options
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bats and Bats libs
        uses: ./
        with:
          bats-version: ${{ matrix.version }
          support-clean: "false"
          assert-clean: "false"
          detik-install: "true"
          file-install: "true"
      - name: Execute test to check Bats-support
        run: |
          cd /tmp/bats-support/
          bats test
      - name: Execute test to check  Bats-assert
        run: |
          cd /tmp/bats-assert/
          bats test
      - name: Execute example tests
        run:
          bats -T -p tests
